project:
  type: book
  output-dir: docs


# jupyter: python3
jupyter: ds_handbook
jupyter-python: "/Users/jamiehudson/Documents/miniconda3/envs/ds_handbook/bin/python"

book:
  title: "Data Science at SAMY"
  author: ""
  sidebar: 
    # style: floating
    # background: light
    search: true
    collapse-level: 1
    border: true
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - quarto_docs/summary.qmd
    - text: "---"
    - part: "Case Studies"
      chapters:
        - quarto_docs/peaks_pits_workflow.qmd
        - quarto_docs/conversation_landscape.qmd
    - text: "---"
    - part: "Project work"
      chapters:
        - quarto_docs/project_management.qmd
        - quarto_docs/project_players.qmd
    - text: "---"
    - part: "Development"
      chapters:
        - quarto_docs/packages.qmd
        - quarto_docs/package_development.qmd
        - quarto_docs/testing.qmd
    - text: "---"
    - part: "Modelling"
      chapters:
        - quarto_docs/modelling_overview.qmd
        - quarto_docs/modelling_data.qmd
        - quarto_docs/model_finetuning.qmd
        - quarto_docs/logistic_regression.qmd
        - quarto_docs/setfit.qmd
        - quarto_docs/vanilla_finetuning.qmd
        - quarto_docs/model_evaluation.qmd
    - text: "---"
    - part: "Tips and Tricks"
      chapters:
        - quarto_docs/code_best_practices.qmd
        - quarto_docs/data_cleaning.qmd
        - quarto_docs/calling_apis.qmd
        - quarto_docs/resources.qmd
  bread-crumbs: false
    
bibliography: references.bib

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    number-depth: 2
    lightbox: true
    code-block-bg: true
    code-block-border-left: true
    theme: 
      light: lumen
      dark: [lumen, theme-dark.scss]
  # pdf:
  #   documentclass: scrreprt

editor: source
